### ISSUE TITLE
bat is actually called batcat on debian or ubuntu

### ISSUE THREAD

**Issue by jkremser** [jkremser/kubectl-kedify#8]
`bat -> batcat`

https://github.com/kedify/examples/blob/ce868bd46dbeaeae3f2389f073af6789a5b0a59f/killercoda/http-scaler/assets/init-kedify.sh#L16

**Comment by wozniakjan** [comment]
I think it's only ubuntu thing to call `bat` with `batcat` due to some other package claiming the name earlier

**Comment by jkremser** [comment]
done in https://github.com/jkremser/kubectl-kedify/commit/3d713f4daae74e595d6d9d5ac157cfad0d9bd0c3
